#!/usr/bin/env python
#
# $Id: template.py 196 2007-03-29 08:03:42Z ltsai $
#
# Copyright 2007 Platform Computing Corporation.
#
# Licensed under GPL version 2; See LICENSE file for details.
# 

from kusu.autoinstall.scriptfactory import KickstartFactory
from kusu.autoinstall.autoinstall import Script
from kusu.autoinstall.installprofile import Kickstart
from kusu.partitiontool.partitiontool import DiskProfile

def returnBytes(mega):
    return mega * 1000000

def kickstartProfile():
    myDiskProfile = DiskProfile(False)
    for lv in myDiskProfile.lv_dict.values():
        myDiskProfile.delete(lv)

    for lvg in myDiskProfile.lvg_dict.values():
        myDiskProfile.delete(lvg)

    for disk in myDiskProfile.disk_dict.values():
        for part in disk.partition_dict.values():
            myDiskProfile.delete(part)

    myDiskProfile.newPartition('sda', returnBytes(4000) , False, 'ext3', '/')
    myDiskProfile.newPartition('sda', returnBytes(100), False, 'ext3', '/boot')
    myDiskProfile.newPartition('sda', returnBytes(1000), False, 'linux-swap', None)
    myDiskProfile.newPartition('sda', returnBytes(500), False, 'ext3', '/one')
    myDiskProfile.newPartition('sda', returnBytes(500), False, 'ext3', '/two')


    networkprofile = { 'fqhn': 'myhostname.local',
                       'fqhn_use_dhcp': False,
                       'default_gw' : '192.168.1.1',
                       'dns1' : '192.168.1.2',
                       'gw_dns_use_dhcp': False,
                       'interfaces': {'etho': 
                                     {'active_on_boot': True, 
                                      'configure': True,
                                      'use_dhcp': True}}}

    k = Kickstart()
    k.rootpw = 'system'
    k.networkprofile = networkprofile
    k.diskprofile = myDiskProfile
    k.packageprofile = ['@Base']
    k.tz = 'Asia/Singapore'
    k.installsrc = 'http://172.25.208.218/repo/fedora/6/i386/os/'
    k.lang = 'us'
    k.keyboard = 'us'

    return k


script = Script(KickstartFactory(kickstartProfile()))
script.write('/tmp/ff.cfg')


