#!/usr/bin/env bash
# $Id$
#
# Copyright 2007 Platform Computing Corporation.
#
# Licensed under GPL version 2; See LICENSE for details.
#
# Kusu 'faux anaconda' loader

# Preserve the current environment 
envfile="/tmp/anaconda-current-environment.$$.tmp"
/usr/bin/env > $envfile

# links the kusu runtime to /opt
/usr/bin/ln -sf /tmp/updates/opt /opt

# Sets the LANG to a valid value to avoid the garbled text ui
export LANG="en_US.UTF-8"

# setups our environment
source /opt/kusu/bin/kusuenv.sh

# setup /tmp/kusu
/usr/bin/mkdir -p $KUSU_TMP

# launch the Kusu Installer
/usr/bin/python /opt/kusu/bin/installer

if [ $? -eq 0 ]; then 
    # Unset kusu bits
    for key in `/usr/bin/env | /usr/bin/awk -F= '{print $1}' | grep KUSU`; do 
        unset $key > /dev/null 2>&1
    done
    unset LANG > /dev/null 2>&1
    unset PYTHONPATH  > /dev/null 2>&1
 
    
    # Restore the environment when we are done
    source $envfile > /dev/null 2>&1 

    # start thttpd
    /opt/kusu/bin/thttpd -p 80 -h 127.0.0.1 -u root -d /mnt/kusu/depot -l /dev/null 

    # exec the real anaconda
    # Need a better to replace existing -m and --kickstart option in $@
    /usr/bin/anaconda "$@" -m http://127.0.0.1/ --kickstart /tmp/kusu/install_script ;
else
    # in case of problem with the Kusu Installer, we halt
    echo "Something has gone very wrong. Restarting!";
fi

