#!/usr/bin/env bash
# $Id$
#
# Copyright 2007 Platform Computing Corporation.
#
# Licensed under GPL version 2; See LICENSE for details.
#
# Kusu 'faux anaconda' loader

# Preserve the current environment 
envfile="/tmp/anaconda-current-environment.$$.tmp"
/usr/bin/env > $envfile

# links the kusu runtime to /opt
/usr/bin/ln -sf opt /opt

# Sets the LANG to a valid value to avoid the garbled text ui
export LANG="en_US.UTF-8"

# setups our environment and launcher the Kusu Installer
source /opt/kusu/bin/kusudevenv.sh
/usr/bin/python /opt/kusu/bin/installer

# Restore the environment when we are done
source $envfile

# exec the real anaconda
/usr/bin/anaconda $@


