#!/usr/bin/env python
# $Id: kitinfo 2020 2007-08-15 09:09:38Z najib $
#
# Base Kit kitinfo
#
# Copyright 2007 Platform Computing Inc.
#
# Licensed under GPL version 2; See LICENSE for details.
#

kit = {'arch': 'noarch',
 'dependencies': [],
 'license': 'GPL',
 'name': 'lava',
 'description': 'Lava Kit',
 'pkgname': 'kit-lava',
 'removable': True,
 'release': '0',
 'scripts': [],
 'version': '1.0'}
components = [{'arch': 'noarch',
  'comprelease': '0',
  'compversion': '1.0',
  'name': 'component-lava-master-v1.0',
  'description': 'Component for Lava Master',
  'ngtypes': '',
  'ostype': '',
  'osversion': '',
  'pkgname': 'component-lava-master-v1.0'},
  {'arch': 'noarch',
    'comprelease': '0',
    'compversion': '1.0',
    'name': 'component-lava-compute-v1.0',
    'description': 'Component for Lava Compute',
    'ngtypes': '',
    'ostype': '',
    'osversion': '',
    'pkgname': 'component-lava-compute-v1.0'}]
