#!/usr/bin/env python
#
# $Id: template.py 196 2007-03-29 08:03:42Z ltsai $
#
# Copyright 2007 Platform Computing Inc.
#
# Licensed under GPL version 2; See LICENSE file for details.
# 

from kusu.util import util

url = 'http://download.fedora.redhat.com/pub/fedora/linux/core/6/i386/os/'
util.verifyDistro(url, 'fedora', '6')
