#!/usr/bin/env python
# $Id$
#
# Keyboard values for rhel/centos/scientificlinux
#
# Copyright 2007 Platform Computing Inc.
#
# Licensed under GPL version 2; See LICENSE file for details.
#

kbDefault = 'us'

kbMap = \
{   'ar-azerty': 'ar-azerty',
    'ar-azerty-digits': 'ar-azerty-digits',
    'ar-digits': 'ar-digits',
    'ar-qwerty': 'ar-qwerty',
    'ar-qwerty-digits': 'ar-qwerty-digits',
    'be-latin1': 'be-latin1',
    'ben': 'ben',
    'ben-probhat': 'ben-probhat',
    'bg': 'bg',
    'br-abnt2': 'br-abnt2',
    'cf': 'cf',
    'croat': 'croat',
    'cz-lat2': 'cz-lat2',
    'cz-us-qwertz': 'cz-us-qwertz',
    'de': 'de',
    'de-latin1': 'de-latin1',
    'de-latin1-nodeadkeys': 'de-latin1-nodeadkeys',
    'dev': 'dev',
    'dk': 'dk',
    'dk-latin1': 'dk-latin1',
    'dvorak': 'dvorak',
    'es': 'es',
    'et': 'et',
    'fi': 'fi',
    'fi-latin1': 'fi-latin1',
    'fr': 'fr',
    'fr-latin1': 'fr-latin1',
    'fr-latin9': 'fr-latin9',
    'fr-pc': 'fr-pc',
    'fr_CH': 'fr_CH',
    'fr_CH-latin1': 'fr_CH-latin1',
    'gr': 'gr',
    'guj': 'guj',
    'gur': 'gur',
    'hu': 'hu',
    'hu101': 'hu101',
    'is-latin1': 'is-latin1',
    'it': 'it',
    'it-ibm': 'it-ibm',
    'it2': 'it2',
    'jp106': 'jp106',
    'la-latin1': 'la-latin1',
    'mk-utf': 'mk-utf',
    'nl': 'nl',
    'no': 'no',
    'pl2': 'pl2',
    'pt-latin1': 'pt-latin1',
    'ro_win': 'ro_win',
    'ru': 'ru',
    'ru-cp1251': 'ru-cp1251',
    'ru-ms': 'ru-ms',
    'ru.map.utf8ru': 'ru.map.utf8ru',
    'ru1': 'ru1',
    'ru2': 'ru2',
    'ru_win': 'ru_win',
    'sg': 'sg',
    'sg-latin1': 'sg-latin1',
    'sk-qwerty': 'sk-qwerty',
    'slovene': 'slovene',
    'sr-cy': 'sr-cy',
    'sv-latin1': 'sv-latin1',
    'tml-inscript': 'tml-inscript',
    'tml-uni': 'tml-uni',
    'trq': 'trq',
    'ua-utf': 'ua-utf',
    'uk': 'uk',
    'us': 'us',
    'us-acentos': 'us-acentos'}
