#!/usr/bin/env python
# $Id$
#
# Base Kit kitinfo
#
# Copyright 2007 Platform Computing Inc.
#
# Licensed under GPL version 2; See LICENSE for details.
#

kit = {'arch': 'noarch',
 'dependencies': [],
 'license': 'GPL',
 'name': 'base',
 'description': 'Base Kit',
 'pkgname': 'kit-base',
 'removable': False,
 'release': '0',
 'scripts': [],
 'version': '0.9'}
components = [{'arch': 'noarch',
  'comprelease': '0',
  'compversion': '0.9',
  'name': 'base-installer',
  'description': 'Component for Kusu Installer Base',
  'ngtypes': ['installer'],
  'ostype': '',
  'osversion': '',
  'pkgname': 'component-base-installer'},
  {'arch': 'noarch',
    'comprelease': '0',
    'compversion': '0.9',
    'name': 'base-node',
    'description': 'Component for Kusu Node Base',
    'ngtypes': ['installer', 'compute'],
    'ostype': '',
    'osversion': '',
    'pkgname': 'component-base-node'}]
