#!/bin/sh

#   Copyright 2007 Platform Computing Inc
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of version 2 of the GNU General Public License as
# published by the Free Software Foundation.
# 	
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
#

# ------------------  IMPORTANT  ------------------
# This script calls getent to gather all the password, group and shadow 
# files.  The symbolic links in /etc/cfm/$NODEGRP/etc/____  need to be
# updated to point to the files generated by this script.


# The following code generate a new password file 
getent passwd > /etc/cfm/passwd.new
if [ -f /etc/cfm/passwd.getent ]; then
    # Only update it if there are differences
    diff -q /etc/cfm/passwd.getent /etc/cfm/passwd.new
    if [ $? -eq 1 ]; then
	cp /etc/cfm/passwd.new /etc/cfm/passwd.getent
    fi
else
    cp /etc/cfm/passwd.new /etc/cfm/passwd.getent
fi

getent shadow > /etc/cfm/shadow.new
chmod 400 /etc/cfm/shadow.new
if [ -f /etc/cfm/shadow.getent ]; then
    # Only update it if there are differences
    diff -q /etc/cfm/shadow.getent /etc/cfm/shadow.new
    if [ $? -eq 1 ]; then
        cp /etc/cfm/shadow.new /etc/cfm/shadow.getent
        chmod 400 /etc/cfm/shadow.getent
    fi
else
    cp /etc/cfm/shadow.new /etc/cfm/shadow.getent
    chmod 400 /etc/cfm/shadow.getent
fi

getent group  > /etc/cfm/group.new
if [ -f /etc/cfm/group.getent ]; then
    # Only update it if there are differences
    diff -q /etc/cfm/group.getent /etc/cfm/group.new
    if [ $? -eq 1 ]; then
	cp /etc/cfm/group.new /etc/cfm/group.getent
    fi
else
    cp /etc/cfm/group.new /etc/cfm/group.getent
fi
