#!/usr/bin/env python
#
# $Id: template.py 196 2007-03-29 08:03:42Z ltsai $
#
# Copyright 2007 Platform Computing Corporation.
#
# Licensed under GPL version 2; See LICENSE file for details.
# 

from kusu.autogen.scriptfactory import KickstartFactory
from kusu.autogen.autoinstall import Script
from kusu.autogen.installprofile import Kickstart
from kusu.partitiontool.partitiontool import DiskProfile
from kusu.networktool.network import Network
from path import path
import os

def returnBytes(mega):
    return mega * 1000000

def kickstart():
    myDiskProfile = DiskProfile(True)
    myDiskProfile.newPartition('sda', returnBytes(4000) , False, 'ext3', '/')
    myDiskProfile.newPartition('sda', returnBytes(100), False, 'ext3', '/boot')
    myDiskProfile.newPartition('sda', returnBytes(1000), False, 'linux-swap', None)
    myDiskProfile.newPartition('sda', returnBytes(500), False, 'ext3', '/one')
    myDiskProfile.newPartition('sda', returnBytes(500), False, 'ext3', '/two')

    k = Kickstart()
    k.setRootPw('system')
    k.setNetworkProfile(Network('eth0', 'DHCP'))
    k.setDiskProfile(myDiskProfile)
    k.setPackageProfile(['@Base'])
    k.setTZ('Asia/Singapore')
    k.setInstallSRC('http://172.25.208.218/repo/fedora/6/i386/os/')
    k.setAttr('lang', 'us')
    k.setAttr('keybd', 'us')

    return k

template = path(os.getenv('KUSU_ROOT', None)) / \
           'etc' / \
           'templates' / \
           'kickstart.tmpl'

kf = KickstartFactory(str(template))
script = Script(kf)
script.setProfile(kickstart())
script.write('/tmp/ff.cfg')


