#!/bin/sh
#
# S10lsf-master-preconf
#
# The cluster name is "@CLUSTERNAME@"
#

CLUSTERNAME="@CLUSTERNAME@"

LSF_TOPDIR="/opt/lsf"
LSF_CONFDIR="$LSF_TOPDIR/conf"
EGO_CONFDIR="$LSF_CONFDIR/ego/$CLUSTERNAME/kernel"
LSF_WORKDIR="$LSF_TOPDIR/work/$CLUSTERNAME"

# Create EGO configuration directory (sourced via cfmsync)
/usr/bin/install -o lsfadmin $EGO_CONFDIR

# Update the quick start document with the proper cluster name
sed -i -e "s/XXX_clustername_XXX/$CLUSTERNAME/g" \
    $LSF_TOPDIR/7.0/lsf_quick_admin.html

# Update cluster name in scripts
sed -i -e "s/XXX_clustername_XXX/$CLUSTERNAME/g" \
    $LSF_CONFDIR/profile.lsf

sed -i -e "s/XXX_clustername_XXX/$CLUSTERNAME/g" \
    $LSF_CONFDIR/cshrc.lsf

# Initialize work directory for this cluster
/usr/bin/install -o lsfadmin -d $LSF_WORKDIR

WORKDIRS="ego lsf_indir lsf_cmddir logdir"

for dir in $WORKDIRS; do
     /usr/bin/install -o lsfadmin -d $LSF_WORKDIR/$dir
done

# This script runs once only...  hopefully it succeeds the first time :)
rm -f /etc/rc.kusu.d/S10lsf-master-preconf
