#!/bin/sh
#
# S10lsf-compute-preconf
#
# The cluster name is "@CLUSTERNAME@"
#

CLUSTERNAME="@CLUSTERNAME@"

LSF_TOPDIR="/opt/lsf"

sed -i -e "s/XXX_clustername_XXX/$CLUSTERNAME/g" \
    $LSF_TOPDIR/7.0/lsf_quick_admin.html

# Update cluster name in scripts
sed -i -e "s/XXX_clustername_XXX/$CLUSTERNAME/g" \
    $LSF_CONFDIR/profile.lsf

sed -i -e "s/XXX_clustername_XXX/$CLUSTERNAME/g" \
    $LSF_CONFDIR/cshrc.lsf

rm -f /etc/rc.kusu.d/S10lsf-compute-preconf
