#!/bin/sh

GENCONFIG=""
LSFVERSION="7_0_1"
EGOVERSION="1_2"
CLUSTERNAME="master"

LSF_CONFDIR="/opt/lsf/conf"
EGO_CONFDIR="/opt/lsf/ego/kernel/conf"

MASTER_NODEGROUP="lsf-master-candidate"

# Generate LSF host configuration for installer only.
if [ -f /opt/kusu/bin/genconfig ]; then
   export PYTHONPATH=/opt/kusu/lib/python:$PYTHONPATH
   GENCONFIG="/opt/kusu/bin/genconfig"
fi

# XXX: PYTHONPATH Differs on Fedora!!!!

if [ -f /usr/bin/genconfig ]; then
   export PYTHONPATH=/usr/lib/python2.4/site-packages/kusu:$PYTHONPATH
   GENCONFIG="/usr/bin/genconfig"
fi

if [ -z $GENCONFIG ]; then
	echo "Error: unable to locate genconfig"
	exit 1
fi

[ -d /etc/cfm/$MASTER_NODEGROUP ] || mkdir -p /etc/cfm/$MASTER_NODEGROUP
if [ $? -ne 0 ]; then
	echo "Error creating directory /etc/cfm/$MASTER_NODEGROUP"
	exit 1
fi

INSTALLER_SRC_CFMDIR=$( $GENCONFIG nodegroups ngid=1 )
if [ -z "$INSTALLER_SRC_CFMDIR" ]; then
	echo "Fatal error: unable to find installer nodegroup"
	exit 1
fi

cp -ar /etc/cfm/$INSTALLER_SRC_CFMDIR/* /etc/cfm/$MASTER_NODEGROUP
if [ $? -ne 0 ]; then
	echo "Error copying files from /etc/cfm/$INSTALLER_SRC_CFMDIR to /etc/cfm/$MASTER_NODEGROUP"
fi

# Create files into CFM directory
CFM_EGO_CONFDIR="/etc/cfm/$MASTER_NODEGROUP""$EGO_CONFDIR"

[ -d "$CFM_EGO_CONFDIR" ] || mkdir -p "$CFM_EGO_CONFDIR"
if [ $? -ne 0 ]; then
	echo "Error creating directory $CFM_EGO_CONFDIR"
	exit 1
fi

CFM_LSF_CONFDIR="/etc/cfm/$MASTER_NODEGROUP""$LSF_CONFDIR"

[ -d "$CFM_LSF_CONFDIR" ] || mkdir -p "$CFM_LSF_CONFDIR"
if [ $? -ne 0 ]; then
	echo "Error creating directory $CFM_LSF_CONFDIR"
	exit 1
fi

$GENCONFIG lsfcluster_$LSFVERSION $CLUSTERNAME cluster >$CFM_EGO_CONFDIR/ego.cluster.$CLUSTERNAME

$GENCONFIG egoshared_$EGOVERSION $CLUSTERNAME >$CFM_EGO_CONFDIR/ego.shared

$GENCONFIG lsfconf_$LSFVERSION $CLUSTERNAME master >$CFM_LSF_CONFDIR/lsf.conf
$GENCONFIG egoconf_$EGOVERSION $CLUSTERNAME master >$CFM_EGO_CONFDIR/ego.conf

# Generate CFM symlinks
for ng in $( sqlrunner -q 'SELECT ngname FROM nodegroups WHERE ngid != 1 AND ngid < 5' ); do
	CFM_LSF_CONFDIR="/etc/cfm/$ng""$LSF_CONFDIR"
	CFM_EGO_CONFDIR="/etc/cfm/$ng""$EGO_CONFDIR"

	[ -d "$CFM_LSF_CONFDIR" ] || mkdir -p "$CFM_LSF_CONFDIR"
	if [ $? -ne 0 ]; then
		echo "Error creating directory $CFM_LSF_CONFDIR"
		exit 1
	fi

	[ -d "$CFM_EGO_CONFDIR" ] || mkdir -p "$CFM_EGO_CONFDIR"
	if [ $? -ne 0 ]; then
		echo "Error creating directory $CFM_EGO_CONFDIR"
		exit 1
	fi

	$GENCONFIG lsfconf_$LSFVERSION $CLUSTERNAME slave >$CFM_LSF_CONFDIR/lsf.conf
	$GENCONFIG egoconf_$EGOVERSION $CLUSTERNAME slave >$CFM_EGO_CONFDIR/ego.conf
done

rm -f /etc/rc.kusu.d/S11lsf-genconfig
